/**
 * charts.js — Helper for loading static charts generated by the backend
 */

/**
 * Loads an image from the backend static charts folder into an img element
 * @param {string} chartName - The filename of the chart (e.g., 'feature_importance.png')
 * @param {string} imgElementId - The ID of the <img> element to load into
 */
function loadStaticChart(chartName, imgElementId) {
    const imgEl = document.getElementById(imgElementId);
    if (!imgEl) return;
    
    // Add cache-busting query param so it reloads if newly generated
    const ts = new Date().getTime();
    imgEl.src = `/static/charts/${chartName}?t=${ts}`;
    
    // Handle error gracefully
    imgEl.onerror = () => {
        imgEl.style.display = 'none';
        const parent = imgEl.parentElement;
        if (parent && !parent.querySelector('.chart-error')) {
            const errorDiv = document.createElement('div');
            errorDiv.className = 'chart-error';
            errorDiv.innerHTML = `
                <div style="text-align: center; padding: 2rem; color: var(--text-muted);">
                    <i class="fas fa-chart-bar" style="font-size: 2rem; margin-bottom: 1rem;"></i>
                    <p>Chart data not yet generated.</p>
                    <p style="font-size: 0.8rem;">Run the training pipeline first.</p>
                </div>
            `;
            parent.appendChild(errorDiv);
        }
    };
}
